[toolchain]

[features]
resolution = true
skip-lint = false
devnet = true

# [programs.localnet]
# sagent = "SAGEfgw3ncJAvhqBadJ8B377AvPEJ5wGw6jtgGKFueG"

[programs.devnet]
sagent = "SAGEfgw3ncJAvhqBadJ8B377AvPEJ5wGw6jtgGKFueG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./KiraZNkDvqQrP4zd9eE71gySYo1fV6HNVeA2LqZBZSb.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"

#metaplex program
# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# # cp-swap program in mainnet
# [[test.validator.clone]]
# address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

# # cp-swap create_pool_fee_reveiver in mainnet
# [[test.validator.clone]]
# address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

# # cp-swap ammConfig in mainnet
# [[test.validator.clone]]
# address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"

# # raydium-locking program in mainnet
# [[test.validator.clone]]
# address = "LockrWmn6K5twhz3y9w1dQERbmgSaRkfnTeTKbpofwE"

# # raydium-locking authority in mainnet
# [[test.validator.clone]]
# address = "3f7GcQFG397GAaEnv51zR6tsTVihYRydnydDD1cXekxH"

# # metadata program in mainnet
# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# # raydium-locking authority in mainnet
# [[test.validator.clone]]
# address = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
